#!/bin/sh
#
# @name Gazebo vtol15

# @type Hexarotor x
# @class Copter

#. ${R}etc/init.d/rc.mc_defaults

set VEHICLE_TYPE none

## original params set from rc.mc_defaults

# MAV_TYPE_QUADROTOR 2
param set-default MAV_TYPE 13

if param compare IMU_GYRO_RATEMAX 400
then
	param set-default IMU_GYRO_RATEMAX 800
fi

param set-default NAV_ACC_RAD 2

param set-default RTL_RETURN_ALT 30
param set-default RTL_DESCEND_ALT 10

param set-default GPS_UBX_DYNMODEL 6


##These apps should not be here, but it will turn ugly without these
#control_allocator start
mc_rate_control start
mc_att_control start
mc_hover_thrust_estimator start
flight_mode_manager start
mc_pos_control start
land_detector start multicopter


## original params set for x500

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX -0.113
param set-default CA_ROTOR0_PY 0.363
param set-default CA_ROTOR0_KM  -0.01

param set-default CA_ROTOR1_PX -0.113
param set-default CA_ROTOR1_PY 0.223
param set-default CA_ROTOR1_KM -0.01

param set-default CA_ROTOR2_PX 0.181
param set-default CA_ROTOR2_PY 0.189
param set-default CA_ROTOR2_KM 0.01

param set-default CA_ROTOR3_PX -0.113
param set-default CA_ROTOR3_PY -0.223
param set-default CA_ROTOR3_KM 0.01

param set-default CA_ROTOR4_PX -0.113
param set-default CA_ROTOR4_PY -0.363
param set-default CA_ROTOR4_KM 0.01

param set-default CA_ROTOR5_PX 0.181
param set-default CA_ROTOR5_PY -0.189
param set-default CA_ROTOR5_KM -0.01

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 0
param set-default CA_SV_CS1_TYPE 0
param set-default CA_SV_CS2_TYPE 0
param set-default CA_SV_CS3_TYPE 0


param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2

param set-default COM_ARM_EKF_VEL 1.0

param set-default COM_PREARM_MODE 2

#below sim settings

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=vtol15}


param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1


param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106


param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150


param set-default SIM_GZ_EC_MAX1 1196
param set-default SIM_GZ_EC_MAX2 1196
param set-default SIM_GZ_EC_MAX3 1196
param set-default SIM_GZ_EC_MAX4 1196
param set-default SIM_GZ_EC_MAX5 1196
param set-default SIM_GZ_EC_MAX6 1196



param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

#below control law setting
hexcopterbsctrl start
servo_test start
param set-default COM_RC_IN_MODE 1
