#!/bin/sh
#
# @name x250_test
#
# @type Quadrotor x
# @class Copter
#
# @maintainer SkyCaptain
#

#. ${R}etc/init.d/rc.mc_defaults


set VEHICLE_TYPE none

## original params set from rc.mc_defaults

# MAV_TYPE_QUADROTOR 2
param set-default MAV_TYPE 2

if param compare IMU_GYRO_RATEMAX 400
then
	param set-default IMU_GYRO_RATEMAX 800
fi

param set-default NAV_ACC_RAD 2

param set-default RTL_RETURN_ALT 30
param set-default RTL_DESCEND_ALT 10

param set-default GPS_UBX_DYNMODEL 6


##App start in rc.mc_apps. These apps should not be here, but it will turn ugly without these
#control_allocator start
mc_rate_control start
mc_att_control start
mc_hover_thrust_estimator start
flight_mode_manager start
mc_pos_control start
land_detector start multicopter



## PWM output settings
#motors
param set-default PWM_MAIN_TIM0 400
param set-default PWM_MAIN_TIM1 400

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

## control allocation settings

param set-default CA_AIRFRAME 9
#param set-default CA_ROTOR_COUNT 4

#param set-default CA_ROTOR0_PX 0.13
#param set-default CA_ROTOR0_PY 0.22
#param set-default CA_ROTOR0_KM  0.05

#param set-default CA_ROTOR1_PX -0.13
#param set-default CA_ROTOR1_PY -0.20
#param set-default CA_ROTOR1_KM  0.05

#param set-default CA_ROTOR2_PX 0.13
#param set-default CA_ROTOR2_PY -0.22
#param set-default CA_ROTOR2_KM -0.05

#param set-default CA_ROTOR3_PX -0.13
#param set-default CA_ROTOR3_PY 0.20
#param set-default CA_ROTOR3_KM -0.05


##mission settings
param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2

##arming settings
param set-default COM_ARM_WO_GPS 1
param set-default COM_ARM_HFLT_CHK 0
param set-default COM_ARM_CHK_ESCS 0
param set-default COM_ARM_MAG_ANG -1
param set-default COM_ARM_MAG_STR 0
param set-default COM_ARM_SDCARD 0
param set-default COM_ARM_IMU_ACC 1.0
param set-default COM_ARM_IMU_GYR 0.3
param set-default COM_DISARM_PRFLT -1

##channel settings
param set-default RC_MAP_ARM_SW 5
param set-default RC_MAP_FLTMODE 7
param set-default COM_FLTMODE1 2
param set-default COM_FLTMODE4 4
param set-default COM_FLTMODE6 0

##power system settings
param set-default BAT1_SOURCE -1

##control interface settings
param set-default COM_RC_IN_MODE 0

##testing module
#motor_test start
#quadcopterbsctrl start
quadqmodelbsctrl start
#uniftcctrl start
#motor_eff_ctrl start
