#!/bin/sh
#
# @name vtol16

# @type Hexarotor x
# @class Copter
#
# @maintainer SkyCaptain
#

. ${R}etc/init.d/rc.mc_defaults

# MAV_TYPE_HEXAROTOR 13
param set-default MAV_TYPE 13

## PWM output settings
#motors
param set-default PWM_MAIN_TIM0 -1
param set-default PWM_MAIN_TIM1 -1
param set-default PWM_MAIN_TIM2 -1

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106

#servos
param set-default PWM_AUX_TIM0 400
param set-default PWM_AUX_TIM1 400
param set-default PWM_AUX_TIM2 400

#function 1 for constant min, 2 for constant max
param set-default PWM_AUX_FUNC1 1
param set-default PWM_AUX_DIS1 1100
param set-default PWM_AUX_MAX1 1600
param set-default PWM_AUX_MIN1 1100

param set-default PWM_AUX_FUNC2 2
param set-default PWM_AUX_DIS2 1900
param set-default PWM_AUX_MAX2 1900
param set-default PWM_AUX_MIN2 1400

param set-default PWM_AUX_FUNC3 2
param set-default PWM_AUX_DIS3 1600
param set-default PWM_AUX_MAX3 1600
param set-default PWM_AUX_MIN3 1400

param set-default PWM_AUX_FUNC4 1
param set-default PWM_AUX_DIS4 1400
param set-default PWM_AUX_MAX4 1600
param set-default PWM_AUX_MIN4 1400

param set-default PWM_AUX_FUNC5 2
param set-default PWM_AUX_DIS5 1600
param set-default PWM_AUX_MAX5 1600
param set-default PWM_AUX_MIN5 1400

param set-default PWM_AUX_FUNC6 1
param set-default PWM_AUX_DIS6 1400
param set-default PWM_AUX_MAX6 1600
param set-default PWM_AUX_MIN6 1400

param set-default PWM_AUX_FUNC7 1
param set-default PWM_AUX_DIS7 1180
param set-default PWM_AUX_MAX7 1600
param set-default PWM_AUX_MIN7 1180

param set-default PWM_AUX_FUNC8 2
param set-default PWM_AUX_DIS8 1800
param set-default PWM_AUX_MAX8 1800
param set-default PWM_AUX_MIN8 1400

## control allocation settings

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX -0.104
param set-default CA_ROTOR0_PY 0.363
param set-default CA_ROTOR0_KM  -0.01

param set-default CA_ROTOR1_PX -0.104
param set-default CA_ROTOR1_PY 0.223
param set-default CA_ROTOR1_KM -0.01

param set-default CA_ROTOR2_PX 0.191
param set-default CA_ROTOR2_PY 0.189
param set-default CA_ROTOR2_KM 0.01

param set-default CA_ROTOR3_PX -0.104
param set-default CA_ROTOR3_PY -0.223
param set-default CA_ROTOR3_KM 0.01

param set-default CA_ROTOR4_PX -0.104
param set-default CA_ROTOR4_PY -0.363
param set-default CA_ROTOR4_KM 0.01

param set-default CA_ROTOR5_PX 0.191
param set-default CA_ROTOR5_PY -0.189
param set-default CA_ROTOR5_KM -0.01

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2

#param set-default COM_ARM_EKF_VEL 1.0

#param set-default COM_PREARM_MODE 2

#below control law setting

param set-default COM_RC_IN_MODE 1
